### ISSUE TITLE
getAuthToken, getAuthTokenByFeatures returning Authtoken even after calling invalidateAuthToken

### ISSUE THREAD

**Issue by LOG-TAG** [Udinic/AccountAuthenticator#3]
1>calling invalidateAuthToken button The application must call invalidateAuthToken(String, String) to remove the token from the cache, but after clicking the invalidateAuthToken button if we click getAuthTokenByFeatures button it's retrieving toke from cache!!?  how it's retrieving token from deleted cache?? 

 2>If it is loading new token where is the implementation in the method invalidateAuthToken  loading new token?  After invalidating the auth token, where it is calling immediately go back to the "Request an auth token".  (auth token generated after invalidation before invalidation is same!)

**Comment by reinhardt1053** [comment]
getAuthTokenByFeatures will use the stored password to get another token. You need to call mAccountManager.clearPassword(account) to clear out the stored password (client side).

**Comment by LOG-TAG** [comment]
thanks @reinhardt1053
